# Generated by Django 6.0.2 on 2026-05-09 14:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GroupMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "group_messages",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.TextField()),
                ("author", models.TextField()),
                ("genre", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("cover_url", models.TextField(blank=True, null=True)),
                ("isbn", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "books",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="GroupPoll",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("question", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "group_polls",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("sender_id", models.UUIDField()),
                ("receiver_id", models.UUIDField()),
                ("content", models.TextField()),
                ("file_url", models.TextField(blank=True, null=True)),
                ("file_type", models.TextField(blank=True, null=True)),
                ("file_name", models.TextField(blank=True, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "messages",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.TextField(blank=True, null=True)),
                ("full_name", models.TextField(blank=True, null=True)),
                ("username", models.TextField(blank=True, null=True, unique=True)),
                ("avatar_url", models.TextField(blank=True, null=True)),
                ("bio", models.TextField(blank=True, null=True)),
                ("website", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "profiles",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="DirectRecommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("from_user_id", models.UUIDField()),
                ("to_user_id", models.UUIDField()),
                ("message", models.TextField(blank=True, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "book",
                    models.ForeignKey(
                        db_column="book_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.book",
                    ),
                ),
            ],
            options={
                "db_table": "recommendations",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="GroupPollOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("text", models.TextField()),
                (
                    "poll",
                    models.ForeignKey(
                        db_column="poll_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="api.grouppoll",
                    ),
                ),
            ],
            options={
                "db_table": "group_poll_options",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="grouppoll",
            name="creator",
            field=models.ForeignKey(
                db_column="creator_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="api.profile",
            ),
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("user_id", models.UUIDField()),
                ("score", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "book",
                    models.ForeignKey(
                        db_column="book_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.book",
                    ),
                ),
            ],
            options={
                "db_table": "ratings",
                "managed": True,
                "unique_together": {("user_id", "book")},
            },
        ),
        migrations.CreateModel(
            name="ReadingGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("is_public", models.BooleanField(default=True)),
                ("avatar_url", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "creator",
                    models.ForeignKey(
                        db_column="creator_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_groups",
                        to="api.profile",
                    ),
                ),
            ],
            options={
                "db_table": "reading_groups",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="grouppoll",
            name="group",
            field=models.ForeignKey(
                db_column="group_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polls",
                to="api.readinggroup",
            ),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "book",
                    models.ForeignKey(
                        db_column="book_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="api.book",
                    ),
                ),
                (
                    "rating",
                    models.ForeignKey(
                        blank=True,
                        db_column="rating_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.rating",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="api.profile",
                    ),
                ),
            ],
            options={
                "db_table": "reviews",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ReviewComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "review",
                    models.ForeignKey(
                        db_column="review_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="api.review",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.profile",
                    ),
                ),
            ],
            options={
                "db_table": "review_comments",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="LibraryItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("user_id", models.UUIDField()),
                ("status", models.TextField(default="plan_to_read")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "book",
                    models.ForeignKey(
                        db_column="book_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.book",
                    ),
                ),
            ],
            options={
                "db_table": "library",
                "managed": True,
                "unique_together": {("user_id", "book")},
            },
        ),
        migrations.CreateModel(
            name="GroupPollVote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        db_column="option_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="api.grouppolloption",
                    ),
                ),
                (
                    "poll",
                    models.ForeignKey(
                        db_column="poll_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="api.grouppoll",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.profile",
                    ),
                ),
            ],
            options={
                "db_table": "group_poll_votes",
                "managed": True,
                "unique_together": {("poll", "user")},
            },
        ),
        migrations.CreateModel(
            name="Friendship",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("status", models.TextField(default="pending")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "initiator",
                    models.ForeignKey(
                        db_column="initiator_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_friendships",
                        to="api.profile",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        db_column="receiver_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_friendships",
                        to="api.profile",
                    ),
                ),
            ],
            options={
                "db_table": "friendships",
                "managed": True,
                "unique_together": {("initiator", "receiver")},
            },
        ),
        migrations.CreateModel(
            name="ReadingGroupBook",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("status", models.TextField(default="reading")),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        db_column="added_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.profile",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        db_column="book_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.book",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        db_column="group_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="api.readinggroup",
                    ),
                ),
            ],
            options={
                "db_table": "reading_group_books",
                "managed": True,
                "unique_together": {("group", "book")},
            },
        ),
        migrations.CreateModel(
            name="ReadingGroupMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.TextField(default="member")),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("last_read_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        db_column="group_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="api.readinggroup",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        db_column="profile_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_memberships",
                        to="api.profile",
                    ),
                ),
            ],
            options={
                "db_table": "reading_group_memberships",
                "managed": True,
                "unique_together": {("group", "profile")},
            },
        ),
        migrations.CreateModel(
            name="ReviewVote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("vote_type", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "review",
                    models.ForeignKey(
                        db_column="review_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="api.review",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.profile",
                    ),
                ),
            ],
            options={
                "db_table": "review_votes",
                "managed": True,
                "unique_together": {("review", "user")},
            },
        ),
    ]
