# Generated by Django 6.0.2 on 2026-05-08 17:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("title", models.TextField()),
                ("author", models.TextField()),
                ("genre", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("cover_url", models.TextField(blank=True, null=True)),
                ("isbn", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "books",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DirectRecommendation",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("from_user_id", models.UUIDField()),
                ("to_user_id", models.UUIDField()),
                ("message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "recommendations",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Friendship",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("status", models.TextField(default="pending")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "friendships",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GroupMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "group_messages",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GroupPoll",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("question", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "group_polls",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GroupPollOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("text", models.TextField()),
            ],
            options={
                "db_table": "group_poll_options",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GroupPollVote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
            ],
            options={
                "db_table": "group_poll_votes",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LibraryItem",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("user_id", models.UUIDField()),
                ("status", models.TextField(default="plan_to_read")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "library",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("sender_id", models.UUIDField()),
                ("receiver_id", models.UUIDField()),
                ("content", models.TextField()),
                ("file_url", models.TextField(blank=True, null=True)),
                ("file_type", models.TextField(blank=True, null=True)),
                ("file_name", models.TextField(blank=True, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "messages",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("name", models.TextField(blank=True, null=True)),
                ("full_name", models.TextField(blank=True, null=True)),
                ("username", models.TextField(blank=True, null=True, unique=True)),
                ("avatar_url", models.TextField(blank=True, null=True)),
                ("bio", models.TextField(blank=True, null=True)),
                ("website", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "profiles",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("user_id", models.UUIDField()),
                ("score", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ratings",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ReadingGroup",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("is_public", models.BooleanField(default=True)),
                ("avatar_url", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "reading_groups",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ReadingGroupBook",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("status", models.TextField(default="reading")),
                ("added_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "reading_group_books",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ReadingGroupMembership",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("role", models.TextField(default="member")),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "reading_group_memberships",
                "managed": False,
            },
        ),
    ]
